export const labels = {
  en: {
    England: 'English',
    Italy: 'Italian',
    ChooseLanguage: 'Choose language',
    Preferences: 'Configure your preferences',
    Theme: 'Theme',
    Light: 'Light',
    Dark: 'Dark',
    Search: 'Search...',
    GoBack: 'Go Back',
    Author: 'Author:',
    PublishedAt: 'Published At:',
  },
  it: {
    England: 'Englesse',
    Italy: 'Italiano',
    ChooseLanguage: 'Scegli la lingua',
    Preferences: 'Configura le tue preferenze',
    Theme: 'Tema',
    Light: 'Leggera',
    Dark: 'Buia',
    Search: 'Ricerca...',
    GoBack: 'Torna indietro',
    Author: 'Autore:',
    PublishedAt: 'Pubblicato a:',
  },
};
